name: Build kernel (gcc)

on:
  workflow_dispatch:

env:
  Kernel_Link: https://github.com/bread-up/android_kernel_samsung_exynos7870-1 -b h-kernel_enforcing
  GCC: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Clone
         run: |
              sudo apt update && sudo apt install git wget make ccache libncurses* zip -y
              cd && git clone --depth=1 $Kernel_Link kernel && cd kernel
              git clone --depth=1 $GCC /opt/gcc
              make exynos7870-m10lte_defconfig ARCH=arm64 CROSS_COMPILE=/opt/gcc/bin/aarch64-linux-android- ANDROID_PLATFORM_VERSION=10 ANDROID_MAJOR_VERSION=q O=./out
              make ARCH=arm64 CROSS_COMPILE=/opt/gcc/bin/aarch64-linux-android- ANDROID_PLATFORM_VERSION=10 ANDROID_MAJOR_VERSION=q O=./out -j70
  
       - name: Upload to Release
         uses: softprops/action-gh-release@v1
         with:
           files: |
                /home/runner/kernel/out/arch/arm64/boot/Image
                /home/runner/kernel/out/arch/arm64/boot/dtb.img
           name: kernel
           tag_name: ${{ github.run_id }}
           body: |
             kernel for j6lte
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
